package KonversiSuhu;
import java.beans.Statement; 
import java.sql.Connection; 
import java.sql.DriverManager; 
import javax.swing.JOptionPane; 
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kahfi
 */
public class KonversiPanjang extends javax.swing.JFrame {
    DefaultTableModel tabmode; 
    int konversiSatu, konversiDua; 
    double nilai, hasil; 
    String id; 

    /**
     * Creates new form KonversiMassa
     */
    public KonversiPanjang() {
        initComponents();
        Object[] row = { "Nilai", "Konversi", "Hasil"};
        tabmode = new DefaultTableModel(null, row); 
        table_konversi.setModel(tabmode);
       
        tampilkandata(); 
    }
    
       public void tampilkandata(){
        try {
            java.sql.Connection conn = (java.sql.Connection)
                    koneksi.koneksi_db(); 
            String sql = "select * from konversi2"; 
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql); 
            while(hasil.next()){
                String angka = hasil.getString("angka"); 
                String konversi = hasil.getString("konvers"); 
                String has = hasil.getString("hasil"); 
                String [] data = {
                   
                    angka, 
                    konversi, 
                    has
                    
                }; 
                
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
    }
       
         public void hapustable(){
        int row = tabmode.getRowCount(); 
        for(int i=0; i<row; i++){
            tabmode.removeRow(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_konversi = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        comboKonversiS = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboKonversiD = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        fieldNilai = new KonversiSuhu.TextField();
        field_ketKonversi = new KonversiSuhu.TextField();
        fieldHasil = new KonversiSuhu.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Konversi Satuan");

        jButton10.setText("Simpan");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setText("Kembali");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel2.setText("DESC KONVERSI");

        table_konversi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nilai", "Konversi", "Hasil"
            }
        ));
        jScrollPane1.setViewportView(table_konversi);

        jLabel3.setText("MASUKAN NILAI");

        jLabel4.setText("HASIL");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("KONVERSI SATUAN PANJANG");

        jButton11.setText("Reset");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        comboKonversiS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- PILIH SATUAN KONVERSI -", "KM ", "HM", "DAM ", "M", "DM", "CM", "MM" }));
        comboKonversiS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKonversiSActionPerformed(evt);
            }
        });

        jLabel5.setText("KONVERSI DARI");

        comboKonversiD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- PILIH SATUAN KONVERSI -", "KM ", "HM", "DAM ", "M", "DM", "CM", "MM" }));
        comboKonversiD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKonversiDActionPerformed(evt);
            }
        });

        jLabel6.setText("DIKONVERSIKAN KE");

        jButton13.setText("Hitung");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        fieldNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNilaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboKonversiD, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboKonversiS, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldHasil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(field_ketKonversi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addComponent(fieldNilai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(310, 310, 310))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboKonversiS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboKonversiD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jButton13)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field_ketKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(fieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11)
                            .addComponent(jButton12)
                            .addComponent(jButton10))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        hapustable();
        try {
            
            String nilai, ketKonversi, hasil; 
            nilai = fieldNilai.getText(); 
            ketKonversi = field_ketKonversi.getText(); 
            hasil = fieldHasil.getText(); 
            String sql = "insert into konversi2 (angka, konvers, hasil) values('" + nilai + "','" + ketKonversi + "','" + hasil + "')";
            java.sql.Connection conn = (java.sql.Connection)koneksi.koneksi_db();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        tampilkandata();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        this.setVisible(false);
//        MainMenu show = new MainMenu();
//        show.setVisible(true);
          new MainMenu().setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        fieldNilai.setText("");
        field_ketKonversi.setText("");
        fieldHasil.setText("");
        comboKonversiS.setSelectedIndex(0);
        comboKonversiD.setSelectedIndex(0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void comboKonversiSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKonversiSActionPerformed
        konversiSatu =  comboKonversiS.getSelectedIndex(); 
        if(konversiSatu==1){
            id="km"; 
        }
        
        else if(konversiSatu==2){
            id="hm"; 
        }
        else if(konversiSatu==3){
            id="dam"; 
        }
        else if(konversiSatu==4){
            id="m"; 
        }
        else if(konversiSatu==5){
            id="dm"; 
        }
        else if(konversiSatu==6){
            id="cm"; 
        }
        else if(konversiSatu==7){
            id="mm"; 
        }
        else {
            id = "null"; 
        }
      
    }//GEN-LAST:event_comboKonversiSActionPerformed

    private void comboKonversiDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKonversiDActionPerformed
     
    }//GEN-LAST:event_comboKonversiDActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       konversiSatu =  comboKonversiS.getSelectedIndex(); 
       konversiDua = comboKonversiD.getSelectedIndex();
       
       if(konversiSatu + konversiDua == 2 && id=="km"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 1; 
           field_ketKonversi.setText("Kilometer - Kilometer"); 
           fieldHasil.setText(String.valueOf(hasil + " Km"));
           
       }
       
       else if(konversiSatu + konversiDua == 3 && id=="km"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 10; 
           field_ketKonversi.setText("Kilometer - Hektometer"); 
           fieldHasil.setText(String.valueOf(hasil + " Hm"));
           
       }
       else if(konversiSatu + konversiDua == 4 && id=="km"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 100; 
           field_ketKonversi.setText("Kilometer - Dekameter"); 
           fieldHasil.setText(String.valueOf(hasil + " Dam"));
           
       }
       
       else if(konversiSatu + konversiDua == 5 && id=="km"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 1000; 
           field_ketKonversi.setText("Kilometer - Meter"); 
           fieldHasil.setText(String.valueOf(hasil + " M"));
           
       }
       else if(konversiSatu + konversiDua == 6 && id=="km"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 10000; 
           field_ketKonversi.setText("Kilometer - Desimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Dm"));
           
       }
       
       else if(konversiSatu + konversiDua == 7 && id=="km"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 100000; 
           field_ketKonversi.setText("Kilometer - Centimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Cm"));
           
       }
       
       else if(konversiSatu + konversiDua == 8 && id=="km"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 1000_000; 
           field_ketKonversi.setText("Kilometer - Milimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Mm"));
           
       }
       
       else if(konversiSatu + konversiDua == 3 && id=="hm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 10; 
           field_ketKonversi.setText("Hektometer - Kilometer"); 
           fieldHasil.setText(String.valueOf(hasil + " Km"));
           
       }
       
       else if(konversiSatu + konversiDua == 4 && id=="hm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 1; 
           field_ketKonversi.setText("Hektometer - Hektometer"); 
           fieldHasil.setText(String.valueOf(hasil + " Hm"));
           
       }
       
       else if(konversiSatu + konversiDua == 5 && id=="hm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 10; 
           field_ketKonversi.setText("Hektometer - Dekameter"); 
           fieldHasil.setText(String.valueOf(hasil + " Dam"));
           
       }
       else if(konversiSatu + konversiDua == 6 && id=="hm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 100; 
           field_ketKonversi.setText("Hektometer - Meter"); 
           fieldHasil.setText(String.valueOf(hasil + " M"));
           
       }
       else if(konversiSatu + konversiDua == 7 && id=="hm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 1000; 
           field_ketKonversi.setText("Hektometer - Desimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Dm"));
           
       }
       else if(konversiSatu + konversiDua == 8 && id=="hm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 10000; 
           field_ketKonversi.setText("Hektometer - Centimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Cm"));
           
       }
       else if(konversiSatu + konversiDua == 9 && id=="hm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 100000; 
           field_ketKonversi.setText("Hektometer - Milimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Mm"));
           
       }
       else if(konversiSatu + konversiDua == 4 && id=="dam"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 100; 
           field_ketKonversi.setText("Dekameter - Kilometer"); 
           fieldHasil.setText(String.valueOf(hasil + " Km"));
           
       }
       else if(konversiSatu + konversiDua == 5 && id=="dam"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 10; 
           field_ketKonversi.setText("Dekameter - Hektometer"); 
           fieldHasil.setText(String.valueOf(hasil + " Hm"));
           
       }
       else if(konversiSatu + konversiDua == 6 && id=="dam"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 1; 
           field_ketKonversi.setText("Dekameter - Dekameter"); 
           fieldHasil.setText(String.valueOf(hasil + " Dam"));
           
       }
       else if(konversiSatu + konversiDua == 7 && id=="dam"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 10; 
           field_ketKonversi.setText("Dekameter - Meter"); 
           fieldHasil.setText(String.valueOf(hasil + " M"));
           
       }
       else if(konversiSatu + konversiDua == 8 && id=="dam"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 100; 
           field_ketKonversi.setText("Dekameter - Desimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Dm"));
           
       }
       
       else if(konversiSatu + konversiDua == 9 && id=="dam"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 1000; 
           field_ketKonversi.setText("Dekameter - Centimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Cm"));
           
       }
       
       else if(konversiSatu + konversiDua == 10 && id=="dam"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 10000; 
           field_ketKonversi.setText("Dekameter - Milimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Mm"));
           
       }
       else if(konversiSatu + konversiDua == 5 && id=="m"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 1000; 
           field_ketKonversi.setText("Meter - Kilometer"); 
           fieldHasil.setText(String.valueOf(hasil + " Km"));
           
       }
       else if(konversiSatu + konversiDua == 6 && id=="m"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 100; 
           field_ketKonversi.setText("Meter - Hektometer"); 
           fieldHasil.setText(String.valueOf(hasil + " Hektometer"));
           
       }
       else if(konversiSatu + konversiDua == 7 && id=="m"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 10; 
           field_ketKonversi.setText("Meter - Dekameter"); 
           fieldHasil.setText(String.valueOf(hasil + " Dam"));
           
       }
       
       else if(konversiSatu + konversiDua == 8 && id=="m"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 1; 
           field_ketKonversi.setText("Meter - Meter"); 
           fieldHasil.setText(String.valueOf(hasil + " M"));
           
       }
       else if(konversiSatu + konversiDua == 9   && id=="m"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 10; 
           field_ketKonversi.setText("Meter - Desimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Dm"));
           
       }
       
       else if(konversiSatu + konversiDua == 10 && id=="m"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 100; 
           field_ketKonversi.setText("Meter - Centimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Cm"));
           
       }
       else if(konversiSatu + konversiDua == 11 && id=="m"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 1000; 
           field_ketKonversi.setText("Meter - Milimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Mm"));
           
       }
       else if(konversiSatu + konversiDua == 6 && id=="dm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 10000; 
           field_ketKonversi.setText("Desimeter - Kilometer"); 
           fieldHasil.setText(String.valueOf(hasil + " Km"));
           
       }
       
       else if(konversiSatu + konversiDua == 7 && id=="dm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 1000; 
           field_ketKonversi.setText("Desimeter - Hektometer"); 
           fieldHasil.setText(String.valueOf(hasil + " Hm"));
           
       }
       
     
       else if(konversiSatu + konversiDua == 8 && id=="dm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 100; 
           field_ketKonversi.setText("Desimeter - Dekameter"); 
           fieldHasil.setText(String.valueOf(hasil + " Dam"));
           
       }
       else if(konversiSatu + konversiDua == 9 && id=="dm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 10; 
           field_ketKonversi.setText("Desimeter - Meter"); 
           fieldHasil.setText(String.valueOf(hasil + " M"));
           
       }
       else if(konversiSatu + konversiDua == 10 && id=="dm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 1; 
           field_ketKonversi.setText("Desimeter - Desimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Dm"));
           
       }
       else if(konversiSatu + konversiDua == 11 && id=="dm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 10; 
           field_ketKonversi.setText("Desimeter - Centimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Cm"));
           
       }
       
       else if(konversiSatu + konversiDua == 12 && id=="dm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 100; 
           field_ketKonversi.setText("Desimeter - Milimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Mm"));
           
       }
       
       else if(konversiSatu + konversiDua == 7 && id=="cm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 100000; 
           field_ketKonversi.setText("Centimeter - Kilometer"); 
           fieldHasil.setText(String.valueOf(hasil + " Km"));
           
       }
       
     
       else if(konversiSatu + konversiDua == 8 && id=="cm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 10000; 
           field_ketKonversi.setText("Centimeter - Hektometer"); 
           fieldHasil.setText(String.valueOf(hasil + " Hm"));
           
       }
       
       else if(konversiSatu + konversiDua == 9 && id=="cm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 1000; 
           field_ketKonversi.setText("Centimeter - Dekameter"); 
           fieldHasil.setText(String.valueOf(hasil + " Dam"));
           
       }
       else if(konversiSatu + konversiDua == 10 && id=="cm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 100; 
           field_ketKonversi.setText("Centimeter - Meter"); 
           fieldHasil.setText(String.valueOf(hasil + " M"));
           
       }
       else if(konversiSatu + konversiDua == 11 && id=="cm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 10; 
           field_ketKonversi.setText("Centimeter - Desimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Dm"));
           
       }
       else if(konversiSatu + konversiDua == 12 && id=="cm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 1; 
           field_ketKonversi.setText("Centimeter - Centimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Cm"));
           
       }
       else if(konversiSatu + konversiDua == 13 && id=="cm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai * 10; 
           field_ketKonversi.setText("Centimeter - Milimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Mm"));
           
       }
       
       else if(konversiSatu + konversiDua == 8 && id=="mm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 1000000; 
           field_ketKonversi.setText("Milimeter - Kilometer"); 
           fieldHasil.setText(String.valueOf(hasil + " Km"));
           
       }
       else if(konversiSatu + konversiDua == 9 && id=="mm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 100000; 
           field_ketKonversi.setText("Milimeter - Hektometer"); 
           fieldHasil.setText(String.valueOf(hasil + " Hm"));
           
       }
       else if(konversiSatu + konversiDua == 10 && id=="mm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 10000; 
           field_ketKonversi.setText("Milimeter - Dekameter"); 
           fieldHasil.setText(String.valueOf(hasil + " Dam"));
           
       }
       else if(konversiSatu + konversiDua == 11 && id=="mm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 1000; 
           field_ketKonversi.setText("Milimeter - Meter"); 
           fieldHasil.setText(String.valueOf(hasil + " Meter"));
           
       }
       else if(konversiSatu + konversiDua == 12 && id=="mm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 100; 
           field_ketKonversi.setText("Milimeter - Desimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Dm"));
           
       }
       else if(konversiSatu + konversiDua == 13 && id=="mm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 10; 
           field_ketKonversi.setText("Milimeter - Centimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " cm"));
           
       }
       
       else if(konversiSatu + konversiDua == 14 && id=="mm"){
           nilai = Double.valueOf(fieldNilai.getText()); 
           hasil = nilai / 1; 
           field_ketKonversi.setText("Milimeter - Milimeter"); 
           fieldHasil.setText(String.valueOf(hasil + " Mm"));
           
       }
       
     
    
       
       
    }//GEN-LAST:event_jButton13ActionPerformed

    private void fieldNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiPanjang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboKonversiD;
    private javax.swing.JComboBox<String> comboKonversiS;
    private KonversiSuhu.TextField fieldHasil;
    private KonversiSuhu.TextField fieldNilai;
    private KonversiSuhu.TextField field_ketKonversi;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_konversi;
    // End of variables declaration//GEN-END:variables
}
